In [1]:
import numpy as np
import matplotlib.pyplot as plt
import impyute.imputation.ts as ts
import data_create_tool as dct
import pandas as pd
import gzip
import pickle
from tqdm import tqdm_notebook

In [2]:
org_data = dct.Data_split("../dataset/train_set_fin.pickle")

In [3]:
sel_col = ['TIME_INDEX','AREA_INDEX','RAIN','SO2','NOX','NO','NO2','O3','CO','PM10','PM25']
need_f = ['SO2','NOX','NO','NO2','O3','CO','PM10','PM25']
for col in need_f:
    sel_col.append(col+'_FLAG')
org_data.df = org_data.df[sel_col]

In [4]:
tmp = org_data.df.copy()

In [5]:
tmp.keys()

Index(['TIME_INDEX', 'AREA_INDEX', 'RAIN', 'SO2', 'NOX', 'NO', 'NO2', 'O3',
       'CO', 'PM10', 'PM25', 'SO2_FLAG', 'NOX_FLAG', 'NO_FLAG', 'NO2_FLAG',
       'O3_FLAG', 'CO_FLAG', 'PM10_FLAG', 'PM25_FLAG'],
      dtype='object')

In [6]:
for col in tqdm_notebook(['SO2','NOX','NO','NO2','O3','CO','PM10','PM25']):
    flag = col + '_FLAG'
    tmp[col].iloc[np.where(tmp[flag] != 1)] = np.nan

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=8.0), HTML(value='')))

In [7]:
train_data = tmp.dropna()

In [8]:
tmp

,TIME_INDEX,AREA_INDEX,RAIN,SO2,NOX,NO,NO2,O3,CO,PM10,PM25,SO2_FLAG,NOX_FLAG,NO_FLAG,NO2_FLAG,O3_FLAG,CO_FLAG,PM10_FLAG,PM25_FLAG
0,0.0,111121,0.0,0.0050,0.0330,0.0010,0.0320,0.030,0.4,45.0,22.0,1,1,1,1,1,1,1,1
1,0.0,111122,0.0,0.0050,0.0510,0.0130,0.0380,0.027,0.5,59.0,28.0,1,1,1,1,1,1,1,1
2,0.0,111123,0.0,0.0070,0.0340,0.0020,0.0320,0.032,0.5,47.0,20.0,1,1,1,1,1,1,1,1
3,0.0,111124,0.0,0.0060,0.0460,0.0070,0.0390,0.022,0.5,49.0,NaN,1,1,1,1,1,1,1,3
4,0.0,111125,0.0,0.0040,0.0480,0.0040,0.0440,0.019,0.5,49.0,20.0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6386578,15359.0,831155,0.0,0.0060,0.0700,0.0320,0.0380,0.003,0.5,18.0,18.0,1,1,1,1,1,1,1,1
6386579,15359.0,831481,0.0,0.0018,0.0031,0.0002,0.0029,0.029,0.3,25.0,17.0,1,1,1,1,1,1,1,1
6386580,15359.0,831491,0.0,0.0008,0.0018,0.0005,0.0013,0.033,0.2,10.0,9.0,1,1,1,1,1,1,1,1
6386581,15359.0,831492,0.0,0.0008,0.0030,0.0005,0.0026,0.036,0.2,12.0,9.0,1,1,1,1,1,1,1,1
6386582,15359.0,831493,0.0,0.0030,0.0120,0.0020,0.0100,0.026,0.2,16.0,NaN,1,1,1,1,1,1,1,3

In [9]:
train_data

,TIME_INDEX,AREA_INDEX,RAIN,SO2,NOX,NO,NO2,O3,CO,PM10,PM25,SO2_FLAG,NOX_FLAG,NO_FLAG,NO2_FLAG,O3_FLAG,CO_FLAG,PM10_FLAG,PM25_FLAG
0,0.0,111121,0.0,0.0050,0.0330,0.0010,0.0320,0.030,0.4,45.0,22.0,1,1,1,1,1,1,1,1
1,0.0,111122,0.0,0.0050,0.0510,0.0130,0.0380,0.027,0.5,59.0,28.0,1,1,1,1,1,1,1,1
2,0.0,111123,0.0,0.0070,0.0340,0.0020,0.0320,0.032,0.5,47.0,20.0,1,1,1,1,1,1,1,1
4,0.0,111125,0.0,0.0040,0.0480,0.0040,0.0440,0.019,0.5,49.0,20.0,1,1,1,1,1,1,1,1
5,0.0,111131,0.0,0.0040,0.0340,0.0020,0.0320,0.021,0.5,60.0,29.0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6386577,15359.0,831154,0.0,0.0040,0.0540,0.0160,0.0380,0.003,0.4,32.0,13.0,1,1,1,1,1,1,1,1
6386578,15359.0,831155,0.0,0.0060,0.0700,0.0320,0.0380,0.003,0.5,18.0,18.0,1,1,1,1,1,1,1,1
6386579,15359.0,831481,0.0,0.0018,0.0031,0.0002,0.0029,0.029,0.3,25.0,17.0,1,1,1,1,1,1,1,1
6386580,15359.0,831491,0.0,0.0008,0.0018,0.0005,0.0013,0.033,0.2,10.0,9.0,1,1,1,1,1,1,1,1
6386581,15359.0,831492,0.0,0.0008,0.0030,0.0005,0.0026,0.036,0.2,12.0,9.0,1,1,1,1,1,1,1,1

In [10]:
def load_area_split(df):
        data = df
        data = data.sort_values(['AREA_INDEX', 'TIME_INDEX'])
        data.index = range(data['AREA_INDEX'].size)
        area = data['AREA_INDEX']
        index = area[~area.duplicated(keep='first')].index
        area = area.drop_duplicates()
        #area = area.astype('int64')
        area = area.to_numpy()
        result=dict()
        for idx in range(index.size - 1):
            result[area[idx]] = data.loc[index[idx]: index[idx + 1] - 1]
        result[area[area.size - 1]] = data.loc[index[index.size - 1]: data['AREA_INDEX'].size - 1]
        return result

In [11]:
# train_data = load_area_split(df = train_data)
tmp = load_area_split(df = tmp)

In [12]:
print(len(train_data.keys()))
print(len(tmp.keys()))

19
472

In [13]:
s = set(train_data.keys())
tmp3 = [x for x in tmp.keys() if x not in s]

In [14]:
print(tmp3)

[111121, 111122, 111123, 111124, 111125, 111131, 111141, 111142, 111143, 111151, 111152, 111154, 111161, 111162, 111171, 111181, 111191, 111201, 111202, 111212, 111213, 111221, 111231, 111232, 111241, 111242, 111251, 111261, 111262, 111263, 111264, 111273, 111274, 111275, 111281, 111282, 111291, 111301, 111311, 111312, 131111, 131112, 131113, 131114, 131115, 131116, 131117, 131118, 131120, 131121, 131123, 131124, 131125, 131126, 131128, 131129, 131131, 131132, 131141, 131142, 131144, 131145, 131161, 131163, 131191, 131192, 131193, 131194, 131195, 131196, 131197, 131198, 131201, 131202, 131211, 131212, 131222, 131223, 131231, 131232, 131233, 131234, 131241, 131242, 131243, 131244, 131341, 131342, 131343, 131344, 131371, 131372, 131373, 131381, 131382, 131383, 131384, 131385, 131392, 131411, 131412, 131413, 131414, 131415, 131416, 131417, 131441, 131442, 131443, 131451, 131453, 131454, 131471, 131472, 131473, 131474, 131501, 131502, 131531, 131532, 131541, 131551, 131552, 131553, 131554, 131555, 131561, 131562, 131571, 131581, 131591, 131601, 131611, 131621, 132112, 132113, 132401, 132402, 221112, 221131, 221141, 221152, 221162, 221163, 221172, 221181, 221182, 221191, 221192, 221202, 221211, 221212, 221221, 221231, 221233, 221241, 221251, 221271, 221281, 221282, 221283, 221284, 221901, 221902, 238111, 238112, 238120, 238121, 238122, 238123, 238124, 238125, 238126, 238127, 238128, 238129, 238130, 238131, 238132, 238133, 238141, 238142, 238143, 238144, 238145, 238146, 238151, 238152, 238161, 238181, 238182, 238183, 238184, 238191, 238201, 238211, 238241, 238361, 238362, 238371, 238373, 238374, 238375, 238376, 238381, 238401, 238411, 238421, 238431, 238441, 238451, 238461, 238471, 238481, 238491, 238501, 238511, 324115, 324121, 324123, 324124, 324133, 324134, 324135, 324141, 324142, 324148, 324155, 335115, 336111, 336112, 336121, 336124, 336125, 336127, 336128, 336131, 336132, 336133, 336134, 336135, 336141, 336151, 336161, 336221, 336222, 336223, 336352, 336353, 336354, 336355, 336361, 336441, 336451, 336452, 336461, 336471, 336481, 336491, 336501, 336511, 336521, 336531, 336541, 336551, 336561, 336571, 339111, 339112, 339121, 339122, 339123, 339131, 339211, 339312, 422114, 422115, 422121, 422132, 422133, 422141, 422153, 422154, 422155, 422161, 422171, 422201, 422202, 422203, 422204, 422205, 437112, 437113, 437114, 437115, 437116, 437117, 437118, 437119, 437122, 437123, 437124, 437125, 437131, 437132, 437141, 437151, 437152, 437153, 437154, 437161, 437171, 437181, 437191, 437201, 437371, 437401, 437402, 437411, 437421, 437431, 437541, 437542, 437551, 525111, 525112, 525121, 525141, 525142, 525143, 525151, 525161, 525162, 525171, 525172, 525173, 533112, 533113, 533114, 533115, 533116, 534111, 534112, 534114, 534115, 534116, 534341, 534342, 534411, 534421, 534422, 534423, 534424, 534433, 534434, 534441, 534442, 534443, 534444, 534445, 534451, 534461, 534462, 534463, 534471, 534481, 534482, 534491, 534492, 534501, 534502, 534510, 541111, 541112, 541113, 541114, 632121, 632122, 632124, 632132, 632151, 632161, 632171, 632371, 632372, 632421, 632431, 632432, 632441, 632451, 632461, 632472, 632481, 632491, 632501, 632511, 632521, 633122, 633123, 633131, 633211, 633213, 633214, 633311, 633361, 633362, 633411, 633461, 633462, 633471, 633481, 633491, 634111, 735111, 735114, 735115, 735116, 735121, 735122, 735123, 735132, 735133, 735134, 735141, 735142, 735151, 735161, 735162, 735171, 735172, 735181, 735191, 735201, 735351, 735361, 735371, 735381, 735391, 735520, 735521, 735522, 823611, 823621, 823631, 823632, 823633, 823634, 823641, 823651, 823652, 823662, 823671, 823681, 823691, 823701, 823702, 823703, 823704, 823705, 823706, 823801, 823802, 823803, 831151, 831152, 831153, 831154, 831155, 831481, 831491, 831492, 831493]

In [15]:
for t in tmp3:
    print(tmp[t])

   3        3         3        3        3
6309739   NaN   NaN         3         3        3         3        3        3
...       ...   ...       ...       ...      ...       ...      ...      ...
6325090  30.0  12.0         1         1        1         1        1        1
6325091  27.0  12.0         1         1        1         1        1        1
6325092  26.0  12.0         1         1        1         1        1        1
6325093  28.0  14.0         1         1        1         1        1        1
6325094  32.0  13.0         1         1        1         1        1        1

         PM10_FLAG  PM25_FLAG
6309735          3          3
6309736          3          3
6309737          3          3
6309738          3          3
6309739          3          3
...            ...        ...
6325090          1          1
6325091          1          1
6325092          1          1
6325093          1          1
6325094          1          1

[15360 rows x 19 columns]
         TIME_INDEX  AREA_INDEX  RAIN    SO2    NOX     NO    NO2     O3   CO  \
6325095         0.0      831155   0.0  0.004  0.034  0.006  0.027  0.024  0.6
6325096         1.0      831155   0.0  0.006  0.018  0.003  0.015  0.033  0.6
6325097         2.0      831155   0.0  0.006  0.020  0.002  0.017  0.029  0.6
6325098         3.0      831155   0.0  0.005  0.039  0.003  0.035  0.013  0.6
6325099         4.0      831155   0.0  0.005  0.028  0.004  0.024  0.020  0.6
...             ...         ...   ...    ...    ...    ...    ...    ...  ...
6340450     15355.0      831155   0.0  0.006  0.037  0.012  0.025  0.013  0.4
6340451     15356.0      831155   0.0  0.006  0.025  0.004  0.021  0.015  0.4
6340452     15357.0      831155   0.0  0.006  0.022  0.005  0.018  0.016  0.4
6340453     15358.0      831155   0.0  0.006  0.032  0.005  0.027  0.009  0.4
6340454     15359.0      831155   0.0  0.006  0.070  0.032  0.038  0.003  0.5

         PM10  PM25  SO2_FLAG  NOX_FLAG  NO_FLAG  NO2_FLAG  O3_FLAG  CO_FLAG  \
6325095  74.0   NaN         1         1        1         1        1        1
6325096  73.0   NaN         1         1        1         1        1        1
6325097  63.0   NaN         1         1        1         1        1        1
6325098  69.0   NaN         1         1        1         1        1        1
6325099  91.0   NaN         1         1        1         1        1        1
...       ...   ...       ...       ...      ...       ...      ...      ...
6340450  18.0  17.0         1         1        1         1        1        1
6340451  14.0  13.0         1         1        1         1        1        1
6340452   NaN  16.0         1         1        1         1        1        1
6340453  13.0  15.0         1         1        1         1        1        1
6340454  18.0  18.0         1         1        1         1        1        1

         PM10_FLAG  PM25_FLAG
6325095          1          3
6325096          1          3
6325097          1          3
6325098          1          3
6325099          1          3
...            ...        ...
6340450          1          1
6340451          1          1
6340452         11          1
6340453          1          1
6340454          1          1

[15360 rows x 19 columns]
         TIME_INDEX  AREA_INDEX  RAIN     SO2     NOX      NO     NO2     O3  \
6340455         0.0      831481   0.0  0.0037  0.0069  0.0003  0.0066  0.050
6340456         1.0      831481   0.0  0.0039  0.0080  0.0004  0.0076  0.045
6340457         2.0      831481   0.0  0.0032  0.0084  0.0004  0.0080  0.040
6340458         3.0      831481   0.0  0.0033  0.0107  0.0004  0.0102  0.035
6340459         4.0      831481   0.0  0.0040  0.0115  0.0005  0.0110  0.033
...             ...         ...   ...     ...     ...     ...     ...    ...
6355810     15355.0      831481   0.0  0.0022  0.0029  0.0002  0.0027  0.031
6355811     15356.0      831481   0.0  0.0021  0.0031  0.0003  0.0028  0.030
6355812     15357.0      831481   0.0  0.0022  0.0031  0.0004  0.0027  0.031
6355813     15358.0      831481   0.0  0.0019  0.0033  0.0003  0.0030  0.028
6355814     15359.0      831481   0.0  0.0018  0.0031  0.0002  0.0029  0.029

          CO  PM10  PM25  SO2_FLAG  NOX_FLAG  NO_FLAG  NO2_FLAG  O3_FLAG  \
6340455  0.4  62.0  30.0         1         1        1         1        1
6340456  0.4  60.0  27.0         1         1        1         1        1
6340457  0.5  59.0  32.0         1         1        1         1        1
6340458  0.5  67.0  36.0         1         1        1         1        1
6340459  0.5  75.0  48.0         1         1        1         1        1
...      ...   ...   ...       ...       ...      ...       ...      ...
6355810  0.3  26.0  13.0         1         1        1         1        1
6355811  0.3  25.0  17.0         1         1        1         1        1
6355812  0.3  25.0  19.0         1         1        1         1        1
6355813  0.3  24.0  17.0         1         1        1         1        1
6355814  0.3  25.0  17.0         1         1        1         1        1

         CO_FLAG  PM10_FLAG  PM25_FLAG
6340455        1          1          1
6340456        1          1          1
6340457        1          1          1
6340458        1          1          1
6340459        1          1          1
...          ...        ...        ...
6355810        1          1          1
6355811        1          1          1
6355812        1          1          1
6355813        1          1          1
6355814        1          1          1

[15360 rows x 19 columns]
         TIME_INDEX  AREA_INDEX  RAIN     SO2     NOX      NO     NO2     O3  \
6355815         0.0      831491   0.0  0.0061     NaN     NaN     NaN  0.058
6355816         1.0      831491   0.0  0.0046  0.0068  0.0013  0.0054  0.060
6355817         2.0      831491   0.0  0.0047  0.0069  0.0013  0.0055  0.061
6355818         3.0      831491   0.0  0.0035  0.0063  0.0013  0.0050  0.063
6355819         4.0      831491   0.0  0.0040  0.0076  0.0014  0.0062  0.057
...             ...         ...   ...     ...     ...     ...     ...    ...
6371170     15355.0      831491   0.0  0.0012  0.0017  0.0005  0.0012  0.033
6371171     15356.0      831491   0.0  0.0010  0.0017  0.0005  0.0012  0.033
6371172     15357.0      831491   0.0  0.0010  0.0015  0.0004  0.0011  0.034
6371173     15358.0      831491   0.0  0.0008  0.0016  0.0005  0.0011  0.033
6371174     15359.0      831491   0.0  0.0008  0.0018  0.0005  0.0013  0.033

          CO  PM10  PM25  SO2_FLAG  NOX_FLAG  NO_FLAG  NO2_FLAG  O3_FLAG  \
6355815  0.2  52.0   NaN         1        11       11        11        1
6355816  0.2  54.0   NaN         1         1        1         1        1
6355817  0.2  60.0   NaN         1         1        1         1        1
6355818  0.2  56.0   NaN         1         1        1         1        1
6355819  0.2  56.0   NaN         1         1        1         1        1
...      ...   ...   ...       ...       ...      ...       ...      ...
6371170  0.2  16.0   9.0         1         1        1         1        1
6371171  0.2   9.0   9.0         1         1        1         1        1
6371172  0.2  10.0   9.0         1         1        1         1        1
6371173  0.2   9.0   7.0         1         1        1         1        1
6371174  0.2  10.0   9.0         1         1        1         1        1

         CO_FLAG  PM10_FLAG  PM25_FLAG
6355815        1          1          3
6355816        1          1          3
6355817        1          1          3
6355818        1          1          3
6355819        1          1          3
...          ...        ...        ...
6371170        1          1          1
6371171        1          1          1
6371172        1          1          1
6371173        1          1          1
6371174        1          1          1

[15360 rows x 19 columns]
         TIME_INDEX  AREA_INDEX  RAIN     SO2     NOX      NO     NO2     O3  \
6371175         0.0      831492   0.0  0.0017  0.0091  0.0003  0.0089  0.044
6371176         1.0      831492   0.0  0.0017  0.0104  0.0003  0.0101  0.042
6371177         2.0      831492   0.0  0.0017  0.0064  0.0003  0.0061  0.047
6371178         3.0      831492   0.0  0.0017  0.0044  0.0003  0.0042  0.047
6371179         4.0      831492   0.0  0.0017  0.0043  0.0003  0.0040  0.048
...             ...         ...   ...     ...     ...     ...     ...    ...
6386530     15355.0      831492   0.0  0.0011  0.0031  0.0004  0.0027  0.034
6386531     15356.0      831492   0.0  0.0010  0.0042  0.0004  0.0038  0.033
6386532     15357.0      831492   0.0  0.0009  0.0041  0.0004  0.0038  0.033
6386533     15358.0      831492   0.0  0.0007  0.0031  0.0004  0.0027  0.035
6386534     15359.0      831492   0.0  0.0008  0.0030  0.0005  0.0026  0.036

          CO  PM10  PM25  SO2_FLAG  NOX_FLAG  NO_FLAG  NO2_FLAG  O3_FLAG  \
6371175  0.1   8.0   NaN         1         1        1         1        1
6371176  0.1  16.0   NaN         1         1        1         1        1
6371177  0.1  15.0   NaN         1         1        1         1        1
6371178  0.1  17.0   NaN         1         1        1         1        1
6371179  0.1  13.0   NaN         1         1        1         1        1
...      ...   ...   ...       ...       ...      ...       ...      ...
6386530  0.3   9.0   5.0         1         1        1         1        1
6386531  0.4   8.0   7.0         1         1        1         1        1
6386532  0.3  17.0   7.0         1         1        1         1        1
6386533  0.2  12.0   8.0         1         1        1         1        1
6386534  0.2  12.0   9.0         1         1        1         1        1

         CO_FLAG  PM10_FLAG  PM25_FLAG
6371175        1          1          3
6371176        1          1          3
6371177        1          1          3
6371178        1          1          3
6371179        1          1          3
...          ...        ...        ...
6386530        1          1          1
6386531        1          1          1
6386532        1          1          1
6386533        1          1          1
6386534        1          1          1

[15360 rows x 19 columns]
         TIME_INDEX  AREA_INDEX  RAIN    SO2    NOX     NO    NO2     O3   CO  \
6386535     15312.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386536     15313.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386537     15314.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386538     15315.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386539     15316.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386540     15317.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386541     15318.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386542     15319.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386543     15320.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386544     15321.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386545     15322.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386546     15323.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386547     15324.0      831493   0.0    NaN    NaN    NaN    NaN    NaN  NaN
6386548     15325.0      831493   0.0  0.003  0.012  0.003  0.009  0.027  0.3
6386549     15326.0      831493   0.1  0.003  0.008  0.003  0.006  0.033  0.4
6386550     15327.0      831493   0.0  0.003  0.008  0.002  0.005  0.038  0.4
6386551     15328.0      831493   0.0  0.003  0.007  0.002  0.005  0.039  0.3
6386552     15329.0      831493   0.0  0.003  0.006  0.002  0.004  0.040  0.2
6386553     15330.0      831493   0.0  0.003  0.006  0.002  0.004  0.040  0.2
6386554     15331.0      831493   0.0  0.003  0.006  0.002  0.004  0.040  0.2
6386555     15332.0      831493   0.0  0.003  0.006  0.002  0.004  0.039  0.2
6386556     15333.0      831493   0.0  0.003  0.006  0.002  0.004  0.038  0.1
6386557     15334.0      831493   0.0  0.003  0.006  0.002  0.004  0.037  0.2
6386558     15335.0      831493   0.0  0.003  0.006  0.002  0.004  0.035  0.2
6386559     15336.0      831493   0.0  0.003  0.006  0.002  0.004  0.035  0.2
6386560     15337.0      831493   0.0  0.003  0.006  0.002  0.004  0.035  0.2
6386561     15338.0      831493   0.0  0.003  0.007  0.002  0.005  0.033  0.2
6386562     15339.0      831493   0.0  0.003  0.006  0.002  0.004  0.033  0.2
6386563     15340.0      831493   0.0  0.003  0.006  0.002  0.004  0.034  0.2
6386564     15341.0      831493   0.0  0.003  0.005  0.002  0.003  0.036  0.1
6386565     15342.0      831493   0.0  0.003  0.005  0.002  0.003  0.037  0.1
6386566     15343.0      831493   0.0  0.003  0.006  0.002  0.003  0.036  0.1
6386567     15344.0      831493   0.0  0.003  0.006  0.002  0.003  0.034  0.1
6386568     15345.0      831493   0.0  0.003  0.005  0.002  0.003  0.035  0.1
6386569     15346.0      831493   0.0  0.003  0.006  0.003  0.003  0.036  0.1
6386570     15347.0      831493   0.0  0.003  0.005  0.002  0.003  0.037  0.1
6386571     15348.0      831493   0.0  0.003  0.005  0.002  0.003  0.037  0.1
6386572     15349.0      831493   0.0  0.003  0.006  0.003  0.003  0.038  0.1
6386573     15350.0      831493   0.0  0.003  0.006  0.002  0.003  0.039  0.1
6386574     15351.0      831493   0.0  0.003  0.006  0.003  0.003  0.039  0.1
6386575     15352.0      831493   0.0  0.003  0.006  0.002  0.003  0.038  0.1
6386576     15353.0      831493   0.0  0.003  0.006  0.002  0.004  0.036  0.1
6386577     15354.0      831493   0.0  0.003  0.007  0.003  0.004  0.036  0.1
6386578     15355.0      831493   0.0  0.003  0.006  0.002  0.003  0.035  0.1
6386579     15356.0      831493   0.0  0.003  0.006  0.002  0.004  0.034  0.1
6386580     15357.0      831493   0.0  0.003  0.008  0.003  0.005  0.033  0.1
6386581     15358.0      831493   0.0  0.003  0.009  0.003  0.006  0.031  0.2
6386582     15359.0      831493   0.0  0.003  0.012  0.002  0.010  0.026  0.2

         PM10  PM25  SO2_FLAG  NOX_FLAG  NO_FLAG  NO2_FLAG  O3_FLAG  CO_FLAG  \
6386535   NaN   NaN         3         3        3         3        3        3
6386536   NaN   NaN         3         3        3         3        3        3
6386537   NaN   NaN         3         3        3         3        3        3
6386538   NaN   NaN         3         3        3         3        3        3
6386539   NaN   NaN         3         3        3         3        3        3
6386540   NaN   NaN         3         3        3         3        3        3
6386541   NaN   NaN         3         3        3         3        3        3
6386542   NaN   NaN         3         3        3         3        3        3
6386543   NaN   NaN         3         3        3         3        3        3
6386544   NaN   NaN         3         3        3         3        3        3
6386545   NaN   NaN         3         3        3         3        3        3
6386546   NaN   NaN         3         3        3         3        3        3
6386547   NaN   NaN         3         3        3         3        3        3
6386548  28.0   NaN         1         1        1         1        1        1
6386549  33.0   NaN         1         1        1         1        1        1
6386550  44.0   NaN         1         1        1         1        1        1
6386551  52.0   NaN         1         1        1         1        1        1
6386552  47.0   NaN         1         1        1         1        1        1
6386553  29.0   NaN         1         1        1         1        1        1
6386554  28.0   NaN         1         1        1         1        1        1
6386555  22.0   NaN         1         1        1         1        1        1
6386556  24.0   NaN         1         1        1         1        1        1
6386557  19.0   NaN         1         1        1         1        1        1
6386558  22.0   NaN         1         1        1         1        1        1
6386559  31.0   NaN         1         1        1         1        1        1
6386560  27.0   NaN         1         1        1         1        1        1
6386561  26.0   NaN         1         1        1         1        1        1
6386562  25.0   NaN         1         1        1         1        1        1
6386563  23.0   NaN         1         1        1         1        1        1
6386564  19.0   NaN         1         1        1         1        1        1
6386565  19.0   NaN         1         1        1         1        1        1
6386566  13.0   NaN         1         1        1         1        1        1
6386567  15.0   NaN         1         1        1         1        1        1
6386568  16.0   NaN         1         1        1         1        1        1
6386569  15.0   NaN         1         1        1         1        1        1
6386570  16.0   NaN         1         1        1         1        1        1
6386571  19.0   NaN         1         1        1         1        1        1
6386572  17.0   NaN         1         1        1         1        1        1
6386573  13.0   NaN         1         1        1         1        1        1
6386574  12.0   NaN         1         1        1         1        1        1
6386575  17.0   NaN         1         1        1         1        1        1
6386576  16.0   NaN         1         1        1         1        1        1
6386577  13.0   NaN         1         1        1         1        1        1
6386578  13.0   NaN         1         1        1         1        1        1
6386579  11.0   NaN         1         1        1         1        1        1
6386580  14.0   NaN         1         1        1         1        1        1
6386581  14.0   NaN         1         1        1         1        1        1
6386582  16.0   NaN         1         1        1         1        1        1

         PM10_FLAG  PM25_FLAG
6386535          3          3
6386536          3          3
6386537          3          3
6386538          3          3
6386539          3          3
6386540          3          3
6386541          3          3
6386542          3          3
6386543          3          3
6386544          3          3
6386545          3          3
6386546          3          3
6386547          3          3
6386548          1          3
6386549          1          3
6386550          1          3
6386551          1          3
6386552          1          3
6386553          1          3
6386554          1          3
6386555          1          3
6386556          1          3
6386557          1          3
6386558          1          3
6386559          1          3
6386560          1          3
6386561          1          3
6386562          1          3
6386563          1          3
6386564          1          3
6386565          1          3
6386566          1          3
6386567          1          3
6386568          1          3
6386569          1          3
6386570          1          3
6386571          1          3
6386572          1          3
6386573          1          3
6386574          1          3
6386575          1          3
6386576          1          3
6386577          1          3
6386578          1          3
6386579          1          3
6386580          1          3
6386581          1          3
6386582          1          3

In [23]:
import impyute.imputation.ts as ts
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [32]:
imp_mean = IterativeImputer(random_state=0)
imp_mean.fit(train_data[[ 'SO2', 'NOX', 'NO', 'NO2', 'O3',
       'CO', 'PM10', 'PM25']])

IterativeImputer(random_state=0)

In [36]:
imp_data[area][:][3:11]

array([[3.00000e+00, 1.11121e+05, 0.00000e+00, 5.00000e-03, 3.20000e-02,
        2.00000e-03, 3.00000e-02, 2.10000e-02, 5.00000e-01, 5.20000e+01,
        2.50000e+01, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
        1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00],
       [4.00000e+00, 1.11121e+05, 0.00000e+00, 5.00000e-03, 4.40000e-02,
        2.00000e-03, 4.20000e-02, 1.00000e-02, 6.00000e-01, 5.20000e+01,
        2.50000e+01, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
        1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00],
       [5.00000e+00, 1.11121e+05, 0.00000e+00, 5.00000e-03, 5.30000e-02,
        4.00000e-03, 4.90000e-02, 5.00000e-03, 7.00000e-01, 4.80000e+01,
        2.50000e+01, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
        1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00],
       [6.00000e+00, 1.11121e+05, 0.00000e+00, 5.00000e-03, 6.30000e-02,
        1.20000e-02, 5.10000e-02, 4.00000e-03, 6.00000e-01, 5.10000e+01,
        2.80000e+01, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
        1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00],
       [7.00000e+00, 1.11121e+05, 0.00000e+00, 5.00000e-03, 6.50000e-02,
        1.70000e-02, 4.80000e-02, 9.00000e-03, 6.00000e-01, 5.20000e+01,
        2.60000e+01, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
        1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00],
       [8.00000e+00, 1.11121e+05, 0.00000e+00, 6.00000e-03, 5.30000e-02,
        9.00000e-03, 4.40000e-02, 1.70000e-02, 5.00000e-01, 6.40000e+01,
        2.60000e+01, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
        1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00],
       [9.00000e+00, 1.11121e+05, 0.00000e+00, 6.00000e-03, 4.00000e-02,
        6.00000e-03, 3.40000e-02, 3.30000e-02, 6.00000e-01, 5.70000e+01,
        2.40000e+01, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
        1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00],
       [1.00000e+01, 1.11121e+05, 0.00000e+00, 7.00000e-03, 3.80000e-02,
        7.00000e-03, 3.10000e-02, 3.90000e-02, 6.00000e-01, 5.20000e+01,
        2.30000e+01, 1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00,
        1.00000e+00, 1.00000e+00, 1.00000e+00, 1.00000e+00]])

In [33]:
imp_data = tmp.copy()
for area in tqdm_notebook(imp_data.keys()):
    imp_data[area] = imp_data[area].to_numpy()
    imp_data[area]= imp_mean.transform(imp_data[area][3:11])
    imp_data[area] = pd.DataFrame(data=imp_data[area],columns=['TIME_INDEX', 'AREA_INDEX', 'RAIN', 'SO2', 'NOX', 'NO', 'NO2', 'O3',
       'CO', 'PM10', 'PM25', 'SO2_FLAG', 'NOX_FLAG', 'NO_FLAG', 'NO2_FLAG',
       'O3_FLAG', 'CO_FLAG', 'PM10_FLAG', 'PM25_FLAG'])
    # try:   
    # except:
    #     print(area)

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=472.0), HTML(value='')))

ValueError: X has 19 features, but this SimpleImputer is expecting 8 features as input.

In [28]:
imp_data[131120]

,TIME_INDEX,AREA_INDEX,RAIN,SO2,NOX,NO,NO2,O3,CO,PM10,PM25,SO2_FLAG,NOX_FLAG,NO_FLAG,NO2_FLAG,O3_FLAG,CO_FLAG,PM10_FLAG,PM25_FLAG
0,0.0,131120.0,0.0,0.004,0.052,0.013,0.039,0.020265,0.6,52.0,27.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0
1,1.0,131120.0,0.0,0.004,0.053,0.016,0.037,0.020370,0.6,47.0,29.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0
2,2.0,131120.0,0.0,0.004,0.048,0.011,0.037,0.019898,0.7,48.0,22.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0
3,3.0,131120.0,0.0,0.005,0.035,0.005,0.030,0.025775,0.7,48.0,23.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0
4,4.0,131120.0,0.0,0.005,0.048,0.013,0.035,0.023446,0.7,56.0,27.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15355,15355.0,131120.0,0.0,0.001,0.154,0.109,0.046,-0.006746,1.1,35.0,7.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0
15356,15356.0,131120.0,0.0,0.001,0.152,0.107,0.046,-0.006477,1.2,41.0,8.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0
15357,15357.0,131120.0,0.0,0.001,0.156,0.109,0.047,-0.010944,1.4,35.0,7.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0
15358,15358.0,131120.0,0.0,0.001,0.154,0.110,0.045,-0.006764,1.1,32.0,6.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0
15359,15359.0,131120.0,0.0,0.000,0.090,0.050,0.039,-0.000017,0.9,20.0,4.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0

In [21]:
with gzip.open('iterative.pickle','wb')as f:
    pickle.dump(imp_data,f)
del(imp_data)

In [84]:
imp_data = tmp.copy()